/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sumandk_com_sumandk_MainActivity */

#ifndef _Included_sumandk_com_sumandk_MainActivity
#define _Included_sumandk_com_sumandk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL sumandk_com_sumandk_MainActivity_calcularSuma
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
